# Generated by Django 4.0.3 on 2022-03-26 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Circuit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom de la tournée')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Description de la tournée')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('update_datetime', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('address', models.CharField(max_length=1000, verbose_name='Adresse')),
            ],
        ),
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('morning_command', models.CharField(choices=[('0', 'Pas de commande'), ('1', 'Commande')], max_length=2, verbose_name='Commande Midi')),
                ('evening_command', models.CharField(choices=[('0', 'Pas de commande'), ('1', 'Commande')], max_length=2, verbose_name='Commande Soir')),
                ('day_date_command', models.IntegerField(verbose_name='Jour')),
                ('month_date_command', models.IntegerField(verbose_name='Mois')),
                ('year_date_command', models.IntegerField(verbose_name='Année')),
                ('client', models.ManyToManyField(to='manager.client', verbose_name='Client lié')),
            ],
        ),
        migrations.CreateModel(
            name='DefaultCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(choices=[('0', 'Pain'), ('1', 'Soupe'), ('2', 'Entrée'), ('3', 'Plat'), ('4', 'Dessert'), ('5', 'Fruit'), ('6', 'Yaourt'), ('7', 'EK'), ('8', 'FR'), ('9', 'Légumes')], db_index=True, max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nourriture')),
                ('price', models.CharField(max_length=100, verbose_name='Prix')),
                ('category', models.CharField(choices=[('0', 'Pain'), ('1', 'Soupe'), ('2', 'Entrée'), ('3', 'Plat'), ('4', 'Dessert'), ('5', 'Fruit'), ('6', 'Yaourt'), ('7', 'EK'), ('8', 'FR'), ('9', 'Légumes')], db_index=True, max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Planning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circuit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manager.circuit')),
                ('command', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manager.command')),
            ],
        ),
        migrations.AddField(
            model_name='command',
            name='food',
            field=models.ManyToManyField(to='manager.food', verbose_name='Plat commandé'),
        ),
        migrations.AddField(
            model_name='client',
            name='default_command',
            field=models.ManyToManyField(to='manager.defaultcommand'),
        ),
    ]
