# Generated by Django 4.0.3 on 2022-03-27 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_remove_client_default_command_client_default_command'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defaultcommand',
            name='choice',
        ),
        migrations.AddField(
            model_name='defaultcommand',
            name='default',
            field=models.CharField(choices=[(1, 'adz'), (2, 'attaque')], default=1, max_length=10, verbose_name='Plats réguliers'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='client',
            name='default_command',
        ),
        migrations.AddField(
            model_name='client',
            name='default_command',
            field=models.ManyToManyField(to='manager.defaultcommand'),
        ),
    ]
