# Generated by Django 4.0.3 on 2022-03-27 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_remove_defaultcommand_choice_defaultcommand_default_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='command',
            name='client',
        ),
        migrations.AddField(
            model_name='command',
            name='client',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='manager.client', verbose_name='Client lié'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='defaultcommand',
            name='default',
            field=models.CharField(choices=[('3', 'Pasteque'), ('4', 'Cassoulet'), ('5', 'Gruyere')], max_length=10, verbose_name='Plats réguliers'),
        ),
    ]
