# Generated by Django 4.0.3 on 2022-03-27 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_remove_command_client_command_client_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['last_name', 'first_name']},
        ),
        migrations.AddField(
            model_name='client',
            name='circuit',
            field=models.ManyToManyField(to='manager.circuit'),
        ),
        migrations.AlterField(
            model_name='defaultcommand',
            name='default',
            field=models.CharField(choices=[('0', 'Pain'), ('1', 'Soupe'), ('2', 'Entrée'), ('3', 'Plat'), ('4', 'Dessert'), ('5', 'Fruit'), ('6', 'Yaourt'), ('7', 'EK'), ('8', 'FR'), ('9', 'Légumes')], max_length=10, verbose_name='Plats réguliers'),
        ),
    ]
