# Generated by Django 4.0.3 on 2022-03-27 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_remove_planning_command_planning_command'),
    ]

    operations = [
        migrations.AddField(
            model_name='planning',
            name='month_date_planning',
            field=models.IntegerField(default=1, verbose_name='Mois'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='planning',
            name='year_date_planning',
            field=models.IntegerField(default=1, verbose_name='Année'),
            preserve_default=False,
        ),
    ]
