# Generated by Django 4.0.3 on 2022-03-27 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0011_planning_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='manager.client', verbose_name='Client lié'),
        ),
        migrations.RemoveField(
            model_name='planning',
            name='command',
        ),
        migrations.AddField(
            model_name='planning',
            name='command',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, to='manager.command', verbose_name='Les commandes effectuées.'),
            preserve_default=False,
        ),
    ]
