# Generated by Django 4.0.3 on 2022-03-27 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0012_alter_command_client_remove_planning_command_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='planning',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.PROTECT, related_name='Command', to='manager.planning'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='planning',
            name='command',
        ),
        migrations.AddField(
            model_name='planning',
            name='command',
            field=models.ManyToManyField(related_name='Planning', to='manager.command', verbose_name='Les commandes effectuées.'),
        ),
    ]
