# Generated by Django 4.0.3 on 2022-03-27 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0013_command_planning_remove_planning_command_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100, verbose_name='Nom')),
            ],
        ),
        migrations.CreateModel(
            name='EveningNumberCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Nom')),
            ],
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100, verbose_name='Nom')),
            ],
        ),
        migrations.CreateModel(
            name='MorningNumberCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Nom')),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100, verbose_name='Nom')),
            ],
        ),
        migrations.RemoveField(
            model_name='command',
            name='day_date_command',
        ),
        migrations.RemoveField(
            model_name='command',
            name='evening_command',
        ),
        migrations.RemoveField(
            model_name='command',
            name='month_date_command',
        ),
        migrations.RemoveField(
            model_name='command',
            name='morning_command',
        ),
        migrations.RemoveField(
            model_name='command',
            name='year_date_command',
        ),
        migrations.AddField(
            model_name='command',
            name='day_date_command',
            field=models.ManyToManyField(to='manager.day', verbose_name='Jour'),
        ),
        migrations.AddField(
            model_name='command',
            name='evening_command',
            field=models.ManyToManyField(to='manager.eveningnumbercommand', verbose_name='Commande Soir'),
        ),
        migrations.AddField(
            model_name='command',
            name='month_date_command',
            field=models.ManyToManyField(to='manager.month', verbose_name='Mois'),
        ),
        migrations.AddField(
            model_name='command',
            name='morning_command',
            field=models.ManyToManyField(to='manager.morningnumbercommand', verbose_name='Commande Midi'),
        ),
        migrations.AddField(
            model_name='command',
            name='year_date_command',
            field=models.ManyToManyField(to='manager.year', verbose_name='Année'),
        ),
    ]
