# Generated by Django 4.0.3 on 2022-03-27 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0015_remove_command_evening_command_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='command',
            name='evening_command',
        ),
        migrations.AddField(
            model_name='command',
            name='evening_command',
            field=models.ManyToManyField(to='manager.eveningnumbercommand', verbose_name='Commande Soir'),
        ),
        migrations.RemoveField(
            model_name='command',
            name='morning_command',
        ),
        migrations.AddField(
            model_name='command',
            name='morning_command',
            field=models.ManyToManyField(to='manager.morningnumbercommand', verbose_name='Commande Midi'),
        ),
        migrations.AlterField(
            model_name='eveningnumbercommand',
            name='number',
            field=models.IntegerField(verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='morningnumbercommand',
            name='number',
            field=models.IntegerField(verbose_name='Nom'),
        ),
    ]
