# Generated by Django 4.0.3 on 2022-03-27 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0017_remove_command_evening_command_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planning',
            name='circuit',
        ),
    ]
