# Generated by Django 4.0.3 on 2022-03-27 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0018_remove_planning_circuit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='command',
            name='planning',
        ),
        migrations.DeleteModel(
            name='Planning',
        ),
    ]
