# Generated by Django 4.0.3 on 2022-03-27 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0019_remove_command_planning_delete_planning'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='command',
            name='day_date_command',
        ),
        migrations.AddField(
            model_name='command',
            name='day_date_command',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='manager.day', verbose_name='Jour'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='command',
            name='evening_command',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.eveningnumbercommand', verbose_name='Commande Soir'),
        ),
        migrations.RemoveField(
            model_name='command',
            name='month_date_command',
        ),
        migrations.AddField(
            model_name='command',
            name='month_date_command',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='manager.month', verbose_name='Mois'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='command',
            name='morning_command',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.morningnumbercommand', verbose_name='Commande Midi'),
        ),
        migrations.RemoveField(
            model_name='command',
            name='year_date_command',
        ),
        migrations.AddField(
            model_name='command',
            name='year_date_command',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='manager.year', verbose_name='Année'),
            preserve_default=False,
        ),
    ]
