# Generated by Django 4.0.3 on 2022-03-27 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0021_alter_command_day_date_command_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='manager.client'),
        ),
        migrations.AlterField(
            model_name='command',
            name='day_date_command',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='command',
            name='food',
            field=models.ManyToManyField(to='manager.food'),
        ),
        migrations.AlterField(
            model_name='command',
            name='month_date_command',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='command',
            name='year_date_command',
            field=models.IntegerField(),
        ),
    ]
