# Generated by Django 4.0.3 on 2022-03-27 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0022_alter_command_client_alter_command_day_date_command_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='day_date_command',
            field=models.IntegerField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='command',
            name='evening_command',
            field=models.IntegerField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='command',
            name='month_date_command',
            field=models.IntegerField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='command',
            name='morning_command',
            field=models.IntegerField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='command',
            name='year_date_command',
            field=models.IntegerField(verbose_name=''),
        ),
    ]
