# Generated by Django 4.0.3 on 2022-03-27 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0023_alter_command_day_date_command_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.client'),
        ),
    ]
