# Generated by Django 4.0.3 on 2022-03-28 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0024_alter_command_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='default_command',
        ),
        migrations.AddField(
            model_name='client',
            name='default_command',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='manager.defaultcommand'),
            preserve_default=False,
        ),
    ]
