# Generated by Django 4.0.3 on 2022-03-28 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0026_remove_client_default_command_client_default_command'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='command',
            name='food',
        ),
        migrations.AlterField(
            model_name='command',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manager.client'),
        ),
    ]
