# Generated by Django 4.0.3 on 2022-03-29 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0027_remove_command_food_alter_command_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='default_command',
        ),
        migrations.AddField(
            model_name='client',
            name='default_evening_command',
            field=models.ManyToManyField(related_name='default_evening_command', to='manager.defaultcommand'),
        ),
        migrations.AddField(
            model_name='client',
            name='default_morning_command',
            field=models.ManyToManyField(related_name='default_morning_command', to='manager.defaultcommand'),
        ),
    ]
