# Generated by Django 4.0.3 on 2022-04-02 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0028_remove_client_default_command_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeekRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('range', models.IntegerField(verbose_name='')),
            ],
        ),
    ]
