# Generated by Django 4.0.3 on 2022-04-02 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0029_weekrange'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='cellphone',
            field=models.CharField(default=1, max_length=20, verbose_name='Telephone'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='command',
            name='comment',
            field=models.TextField(default=1, verbose_name=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='command',
            name='meals',
            field=models.ManyToManyField(related_name='meals', to='manager.defaultcommand'),
        ),
        migrations.AlterField(
            model_name='weekrange',
            name='range',
            field=models.IntegerField(default=2, verbose_name=''),
        ),
    ]
