# Generated by Django 4.0.3 on 2022-04-05 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0032_client_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EveningNumberCommand',
        ),
        migrations.DeleteModel(
            name='MorningNumberCommand',
        ),
        migrations.RenameField(
            model_name='command',
            old_name='evening_command',
            new_name='command_command',
        ),
        migrations.RemoveField(
            model_name='client',
            name='default_evening_command',
        ),
        migrations.RemoveField(
            model_name='client',
            name='default_morning_command',
        ),
        migrations.RemoveField(
            model_name='command',
            name='evening_meals',
        ),
        migrations.RemoveField(
            model_name='command',
            name='morning_command',
        ),
        migrations.RemoveField(
            model_name='command',
            name='morning_meals',
        ),
        migrations.AddField(
            model_name='client',
            name='client_command',
            field=models.ManyToManyField(related_name='command', to='manager.defaultcommand'),
        ),
        migrations.AddField(
            model_name='command',
            name='meals',
            field=models.ManyToManyField(related_name='meals', to='manager.defaultcommand'),
        ),
    ]
