# Generated by Django 4.0.3 on 2022-04-05 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0033_delete_eveningnumbercommand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='circuit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='manager.circuit'),
        ),
        migrations.AlterField(
            model_name='command',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='manager.client'),
        ),
    ]
