# Generated by Django 4.0.3 on 2022-04-05 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0034_alter_client_circuit_alter_command_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='meals',
            field=models.ManyToManyField(blank=True, related_name='meals', to='manager.defaultcommand'),
        ),
    ]
