# Generated by Django 4.0.3 on 2022-04-05 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0035_alter_command_meals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name=''),
        ),
    ]
