# Generated by Django 4.0.3 on 2022-04-06 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0036_alter_command_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='free',
            field=models.BooleanField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='command',
            name='reduction',
            field=models.FloatField(blank=True, null=True, verbose_name=''),
        ),
    ]
