# Generated by Django 4.0.3 on 2022-04-07 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0038_remove_food_name_alter_command_command_command'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='cellphone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telephone'),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_command',
            field=models.ManyToManyField(blank=True, related_name='command', to='manager.defaultcommand'),
        ),
        migrations.AlterField(
            model_name='client',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Position de tournée'),
        ),
    ]
