# Generated by Django 4.0.3 on 2022-04-18 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0040_command_circuit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultcommand',
            name='default',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manager.food', verbose_name='Plats réguliers'),
        ),
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.CharField(max_length=200),
        ),
    ]
