# Generated by Django 4.0.3 on 2022-04-18 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0042_alter_defaultcommand_default'),
    ]

    operations = [
        migrations.RenameField(
            model_name='circuit',
            old_name='description',
            new_name='description_c',
        ),
    ]
