# Generated by Django 4.0.3 on 2022-04-19 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0043_rename_description_circuit_description_c'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='postcode',
            field=models.CharField(default=1, max_length=1000, verbose_name='00000 Ville'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.CharField(max_length=200, verbose_name='Catégorie'),
        ),
    ]
