# Generated by Django 4.0.3 on 2022-04-20 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0044_client_postcode_alter_food_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='command',
            name='free',
        ),
        migrations.AlterField(
            model_name='client',
            name='circuit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manager.circuit'),
        ),
    ]
