# Generated by Django 4.0.3 on 2022-04-30 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0051_alter_client_circuit_alter_command_circuit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='description',
        ),
        migrations.RemoveField(
            model_name='command',
            name='reduction',
        ),
        migrations.AddField(
            model_name='client',
            name='cellphone2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telephone secondaire'),
        ),
    ]
