# Generated by Django 4.0.3 on 2022-04-30 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0053_client_address_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Commentaire sous TTC')),
                ('cellphone', models.TextField(blank=True, null=True, verbose_name='Telephone Les Elephants')),
                ('company', models.TextField(blank=True, null=True, verbose_name="Nom de l'entreprise")),
                ('address', models.TextField(blank=True, null=True, verbose_name="Adresse de l'entreprise")),
                ('siret', models.TextField(blank=True, null=True, verbose_name='Numéro SIRET')),
            ],
        ),
    ]
