# Generated by Django 4.0.3 on 2022-04-30 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0054_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='address',
            new_name='address_comp',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='cellphone',
            new_name='cellphone_comp',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='comment',
            new_name='comment_comp',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='company',
            new_name='company_comp',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='siret',
            new_name='siret_comp',
        ),
    ]
