# Generated by Django 4.0.3 on 2022-04-30 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0055_rename_address_company_address_comp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='circuit',
            name='description_c',
        ),
        migrations.AlterField(
            model_name='company',
            name='comment_comp',
            field=models.TextField(blank=True, max_length=240, null=True, verbose_name='Commentaire sous TTC'),
        ),
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.CharField(max_length=200, verbose_name='Plat'),
        ),
    ]
