# Generated by Django 4.0.3 on 2022-05-01 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0056_remove_circuit_description_c_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='command',
            index=models.Index(fields=['day_date_command', 'month_date_command', 'year_date_command', 'client'], name='manager_com_day_dat_26e1bc_idx'),
        ),
    ]
