# Generated by Django 4.0.3 on 2022-05-03 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0057_command_manager_com_day_dat_26e1bc_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['order'], name='manager_cli_order_98aaf0_idx'),
        ),
    ]
