# Generated by Django 4.0.3 on 2022-05-03 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0058_client_manager_cli_order_98aaf0_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='order',
            field=models.CharField(default='0', max_length=1000, verbose_name='Position de tournée'),
        ),
    ]
