# Generated by Django 4.0.3 on 2022-05-03 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0059_alter_client_order'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='client',
            name='manager_cli_order_98aaf0_idx',
        ),
        migrations.AlterField(
            model_name='client',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Position de tournée'),
        ),
    ]
