# Generated by Django 4.0.3 on 2022-05-03 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0060_remove_client_manager_cli_order_98aaf0_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='circuit',
            name='order_c',
            field=models.IntegerField(default=0, verbose_name='Position de tournée'),
        ),
    ]
