# Generated by Django 4.0.3 on 2022-05-03 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0061_circuit_order_c'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['circuit__order_c', 'last_name', 'first_name']},
        ),
    ]
