# Generated by Django 4.0.3 on 2022-05-04 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0064_remove_client_manager_cli_order_98aaf0_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.CharField(max_length=200, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='client',
            name='address_details',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Details'),
        ),
        migrations.AlterField(
            model_name='client',
            name='postcode',
            field=models.CharField(max_length=100, verbose_name='00000 Ville'),
        ),
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.TextField(max_length=200, verbose_name='Plat'),
        ),
    ]
