# Generated by Django 4.0.3 on 2022-05-06 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0065_alter_client_address_alter_client_address_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultcommand',
            name='order_food',
            field=models.IntegerField(default=0, verbose_name='Position du plat'),
        ),
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.CharField(max_length=200, verbose_name='Plat'),
        ),
    ]
