# Generated by Django 4.0.3 on 2022-05-07 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0066_defaultcommand_order_food_alter_food_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='circuit',
            name='circuit_color',
            field=models.CharField(default='#ffffff', max_length=10, verbose_name='Couleur de tournée'),
        ),
    ]
